apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.hermes.name }}-job
  labels:
    app.kubernetes.io/name: {{ .Values.hermes.name }}
    helm.sh/chart: {{ template "hermes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  schedule: "10 * * * *"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hermes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.global.istio.sidecar.inject | default false | quote }}

    spec:
      template:
        spec:
          volumes:
            - name: {{ .Values.script.cm }}-volume
              configMap:
                 name: {{ .Values.script.cm }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - hermes
            - -r5000
            - -p1
            - -t1800
            volumeMounts:
            - name: {{ .Values.script.cm }}-volume
              mountPath: "/etc/scripts/"
              readOnly: true
            env:          
            - name: "OTLP_METRICS_ENDPOINT"
              value: {{ .Values.o11y.metrics_endpoint }}
            - name: "OTLP_TRACES_ENDPOINT"
              value: {{ .Values.o11y.traces_endpoint }}
          restartPolicy: Never